import type { AgencyRun, RunStatus } from "../types"

export type ViewKey = "operations" | "catalog" | "agency" | "observability"

export interface QueueItem {
  id: string
  title: string
  project: string
  channel: string
  scheduledFor: string
  status: RunStatus
  confidence: number
}

export interface RoleSummary {
  role: string
  status: string
  agents: number
  tools: string[]
  guardrails: string[]
}

export const fallbackRun: AgencyRun = {
  id: "run_2026_07_12_0942",
  project: "Wingbeat",
  trigger: "Daily cadence deadline plus detected product-concept edits",
  status: "veto_window",
  startedAt: new Date(Date.now() - 1000 * 60 * 31).toISOString(),
  scheduledFor: new Date(Date.now() + 1000 * 60 * 22).toISOString(),
  vetoEndsAt: new Date(Date.now() + 1000 * 60 * 9 + 1000 * 34).toISOString(),
  publishedUrl: undefined,
  package: {
    id: "pkg_build_in_public_001",
    project: "Wingbeat",
    category: "build-in-public",
    whatChanged:
      "The marketing agency loop moved from a static content generator into a dynamic manager that assembles specialist agents per job.",
    whyItMatters:
      "Technical builders need consistent marketing without losing credibility. The new loop makes every claim traceable to project evidence before execution.",
    audience: "Indie developers and small developer-tool teams building in public",
    narrative:
      "Wingbeat now treats marketing like an operating system: gather evidence, choose a story, build missing capability, adapt the package for a channel, and publish after a veto window.",
    supportedClaims: [
      "The roadmap prioritizes an X build-in-public loop first.",
      "The manager dynamically selects specialist roles per run.",
      "Canonical packages preserve source evidence before channel adaptation.",
      "The publishing contract includes an autonomous veto window.",
    ],
    prohibitedClaims: [
      "Do not claim Reddit or CRM are complete.",
      "Do not imply every visual asset is generated by AI in the MVP.",
      "Do not promise unattended publishing without verification.",
    ],
    hooks: [
      "I stopped thinking of marketing automation as a posting bot.",
      "The hard part is not writing the tweet. It is proving the story is real.",
      "Today I made the agency structure visible instead of hiding it behind a spinner.",
    ],
    channelNeutralBody:
      "Wingbeat is turning project activity into source-backed marketing packages. The important shift is that agents do not start with copy. They start with evidence, assign roles, reject weak drafts, and only publish after a short human veto window.",
    evidence: [
      {
        id: "ev_product_laws",
        source: "docs/product-concept.md",
        label: "Product laws",
        detail:
          "No meaningful progress stays private; intent must precede content; execution is autonomous with a veto window.",
      },
      {
        id: "ev_roadmap_arch",
        source: "docs/two-hour-mvp-roadmap.md",
        label: "Dynamic manager architecture",
        detail:
          "The two-hour MVP recommends a manager, specialist registry, shared event log, trace tree, costs, latency, and receipt.",
      },
      {
        id: "ev_contract",
        source: "src/types.ts",
        label: "Shared content contract",
        detail:
          "The app models runs, agent nodes, trace events, evidence, supported claims, and X adaptations.",
      },
    ],
    confidence: 0.87,
    adaptation: {
      channel: "x",
      copy:
        "I stopped treating marketing automation like a posting bot.\n\nWingbeat now starts with evidence, assembles a tiny specialist agency, rejects weak drafts, and only ships after a veto window.\n\nThe goal: no real product progress gets trapped in private notes.",
      asset: "Deterministic dark operator card with the trace tree and veto timer.",
    },
  },
  agents: [
    {
      id: "agent_manager",
      role: "Agency Manager",
      objective: "Select the strongest story and coordinate specialist agents.",
      status: "working",
      startedAt: new Date(Date.now() - 1000 * 60 * 31).toISOString(),
      latencyMs: 18600,
      tokens: 6812,
      costUsd: 0.92,
      output: "Created a build-in-public plan with evidence-first guardrails.",
    },
    {
      id: "agent_intel",
      parentId: "agent_manager",
      role: "Project Intelligence",
      objective: "Refresh project context and identify source-backed facts.",
      status: "passed",
      startedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      finishedAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
      latencyMs: 41200,
      tokens: 5431,
      costUsd: 0.58,
      output: "Collected product laws, MVP milestones, and content contract details.",
    },
    {
      id: "agent_story",
      parentId: "agent_manager",
      role: "Story Detector",
      objective: "Convert recent project movement into credible narratives.",
      status: "passed",
      startedAt: new Date(Date.now() - 1000 * 60 * 29).toISOString(),
      finishedAt: new Date(Date.now() - 1000 * 60 * 21).toISOString(),
      latencyMs: 38300,
      tokens: 4917,
      costUsd: 0.51,
      output: "Selected the agency-visibility angle over a generic roadmap update.",
    },
    {
      id: "agent_strategy",
      parentId: "agent_manager",
      role: "Content Strategist",
      objective: "Choose audience, hook, and build-in-public structure.",
      status: "passed",
      startedAt: new Date(Date.now() - 1000 * 60 * 19).toISOString(),
      finishedAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
      latencyMs: 27400,
      tokens: 3294,
      costUsd: 0.35,
      output: "Recommended a concise X post for technical builders.",
    },
    {
      id: "agent_critic",
      parentId: "agent_manager",
      role: "Editor / Critic",
      objective: "Reject unsupported claims, repetition, and vague phrasing.",
      status: "revising",
      startedAt: new Date(Date.now() - 1000 * 60 * 13).toISOString(),
      latencyMs: 33200,
      tokens: 3820,
      costUsd: 0.44,
      output: "Blocked a stronger claim about complete publishing until live receipt exists.",
    },
    {
      id: "agent_x",
      parentId: "agent_manager",
      role: "X Execution Agent",
      objective: "Prepare X adaptation, start veto window, and publish on silence.",
      status: "queued",
      startedAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
      latencyMs: 9400,
      tokens: 1504,
      costUsd: 0.16,
      output: "Waiting for veto countdown to expire.",
    },
  ],
  events: [
    {
      id: "evt_001",
      runId: "run_2026_07_12_0942",
      agentId: "agent_manager",
      at: new Date(Date.now() - 1000 * 60 * 31).toISOString(),
      type: "spawn",
      title: "Manager accepted cadence job",
      detail: "Trigger combined the daily deadline with recent roadmap edits.",
    },
    {
      id: "evt_002",
      runId: "run_2026_07_12_0942",
      agentId: "agent_intel",
      at: new Date(Date.now() - 1000 * 60 * 27).toISOString(),
      type: "tool",
      title: "Evidence gathered",
      detail: "Read product concept, roadmap, and shared TypeScript contract.",
    },
    {
      id: "evt_003",
      runId: "run_2026_07_12_0942",
      agentId: "agent_story",
      at: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
      type: "handoff",
      title: "Story handed to strategist",
      detail: "Agency visibility scored higher than a feature-list update.",
    },
    {
      id: "evt_004",
      runId: "run_2026_07_12_0942",
      agentId: "agent_critic",
      at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      type: "evaluation",
      title: "Unsupported claim rejected",
      detail: "Removed language implying verified live publishing before receipt exists.",
    },
    {
      id: "evt_005",
      runId: "run_2026_07_12_0942",
      agentId: "agent_x",
      at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
      type: "publish",
      title: "Veto notification queued",
      detail: "X payload is ready and will publish unless blocked before countdown ends.",
    },
  ],
}

export function buildQueue(run: AgencyRun): QueueItem[] {
  const start = run.scheduledFor ? new Date(run.scheduledFor) : new Date()
  const day = 24 * 60 * 60 * 1000

  return [
    {
      id: run.id,
      title: run.package.hooks[0] ?? run.package.whatChanged,
      project: run.project,
      channel: run.package.adaptation.channel.toUpperCase(),
      scheduledFor: start.toISOString(),
      status: run.status,
      confidence: run.package.confidence,
    },
    {
      id: "queue_catalog_reuse",
      title: "Mine unused decision from catalog",
      project: run.project,
      channel: "X",
      scheduledFor: new Date(start.getTime() + day).toISOString(),
      status: "in_review",
      confidence: 0.72,
    },
    {
      id: "queue_asset_system",
      title: "Show the reusable asset pipeline",
      project: run.project,
      channel: "X",
      scheduledFor: new Date(start.getTime() + day * 2).toISOString(),
      status: "running",
      confidence: 0.69,
    },
    {
      id: "queue_recovery",
      title: "Recover overdue cadence if laptop was offline",
      project: run.project,
      channel: "X",
      scheduledFor: new Date(start.getTime() + day * 4).toISOString(),
      status: "overdue",
      confidence: 0.64,
    },
  ]
}

export function buildRoleSummaries(run: AgencyRun): RoleSummary[] {
  const grouped = new Map<string, RoleSummary>()

  run.agents.forEach((agent) => {
    const current = grouped.get(agent.role)
    const base: RoleSummary = current ?? {
      role: agent.role,
      status: agent.status,
      agents: 0,
      tools: toolsForRole(agent.role),
      guardrails: guardrailsForRole(agent.role),
    }

    grouped.set(agent.role, {
      ...base,
      status: agent.status,
      agents: base.agents + 1,
    })
  })

  return Array.from(grouped.values())
}

function toolsForRole(role: string): string[] {
  if (role.includes("Manager")) return ["delegate", "trace-store", "policy"]
  if (role.includes("Intelligence")) return ["repo-read", "catalog", "evidence"]
  if (role.includes("Story")) return ["event-log", "claim-map"]
  if (role.includes("Strategist")) return ["audience", "calendar"]
  if (role.includes("Critic") || role.includes("Editor")) return ["eval", "revision"]
  if (role.includes("Execution") || role.includes("X")) return ["telegram", "x-adapter"]
  return ["catalog"]
}

function guardrailsForRole(role: string): string[] {
  if (role.includes("Execution") || role.includes("X")) return ["veto window", "receipt required"]
  if (role.includes("Critic") || role.includes("Editor")) return ["evidence only", "no repetition"]
  if (role.includes("Manager")) return ["dynamic roles", "finish run"]
  return ["source-backed", "channel-neutral package"]
}
